export const  FETCH_ALL_PERSONS = 'FETCH_ALL_PERSONS'
export const  FETCH_PERSONS = 'FETCH_PERSONS'
export const  CREATE_PERSONS = 'CREATE_PERSONS'
export const  UPDATE_PERSONS = 'UPDATE_PERSONS'
export const  DELETE_PERSONS = 'DELETE_PERSONS'
export const FETCH_PERSON_BY_ID = 'FETCH_PERSON_BY_ID'
export const PERSONS_OP_ERROR = 'PERSONS_OP_ERROR'

export const FETCH_ALL_NOTES = 'FETCH_ALL_NOTES'
export const FETCH_NOTES = 'FETCH_NOTES'
export const CREATE_NOTES = 'CREATE_NOTES'
export const UPDATE_NOTES = 'UPDATE_NOTES'
export const DELETE_NOTES = 'DELETE_NOTES'
export const NOTES_OP_ERROR = 'NOTES_OP_ERROR'

export const  NOTES_RECORD = 'notes'
export const  PERSONS_RECORD = 'persons'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_OP_ERROR = 'USER_OP_ERROR'

export const OPERATION_ERROR = 'OPERATION_ERROR'
export const OPERATION_SUCCESS = 'OPERATION_SUCCESS'
export const OPERATION_WAITING = 'OPERATION_WAITING'

export const SET_NOTIFICATION_MESSAGE = 'SET_NOTIFICATION_MESSAGE'
export const CLEAR_NOTIFICATION_MESSAGE = 'CLEAR_NOTIFICATION_MESSAGE'
